browser: edge

environment:
  test:
    active: true
    envName: TST
    baseUrl: https://api.openweathermap.org
    weatherSuffix: /data/2.5/weather
    geoSuffix: /geo/1.0/direct
    appId: 89a2ed8a594cc497a6273490e7ca59dd
